/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-01-20 05:20:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.memberDTO.MemberDTO;
import member.memberDAO.MemberDAO;

public final class MyPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/Layout/Header.jsp", Long.valueOf(1579497072332L));
    _jspx_dependants.put("/Layout/Footer.jsp", Long.valueOf(1579496978508L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.memberDTO.MemberDTO");
    _jspx_imports_classes.add("member.memberDAO.MemberDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String id = (String)session.getAttribute("login");
	MemberDAO dao = new MemberDAO();
	MemberDTO dto = dao.memberInfo(id);
	session.setAttribute("member", dto);

      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');

	String login = (String)session.getAttribute("login");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#header , .footer {\r\n");
      out.write("\t\tborder : 1px black solid;\r\n");
      out.write("\t\twidth : 600px;\r\n");
      out.write("\t\theight : 40px;\r\n");
      out.write("\t\tpadding-top : 12px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#main {\r\n");
      out.write("\t\twidth : 600px;\r\n");
      out.write("\t\tmin-height : 400px;\r\n");
      out.write("\t\tpadding-top : 15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#border {\r\n");
      out.write("\t\tborder : 1px solid black;\r\n");
      out.write("\t}\r\n");
      out.write("\t#table {\r\n");
      out.write("\t\twidth: 450px;\r\n");
      out.write("\t\tborder : 1px solid black;\r\n");
      out.write("\t\tborder-spacing: 0px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#button{\r\n");
      out.write("\t\twidth : 450px;\r\n");
      out.write("\t\ttext-align: right;\r\n");
      out.write("\t\tpadding-top: 15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#link{\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("\t}\r\n");
      out.write("\ta{\r\n");
      out.write("\t\ttext-decoration: none;\r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t\t<div align=\"center\" id = \"header\"  >\r\n");
      out.write("\t\t\t");
if(login != null) {
      out.write("\r\n");
      out.write("\t\t\t\t<a href = \"/MyHome/Member/MyPage.jsp\">MyPage</a> | \r\n");
      out.write("\t\t\t\t<a href = \"/MyHome/Login/Logout.jsp\" style=\"text-decoration: none;\">Logout</a> | \r\n");
      out.write("\t\t\t");
} else {
      out.write("\r\n");
      out.write("\t\t\t\t<a href = \"/MyHome/Login/LoginForm.jsp\">Login</a> | \r\n");
      out.write("\t\t\t\t<a href = \"/MyHome/Member/JoinForm.jsp\" style=\"text-decoration: none;\">Join</a> | \r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t<a href = \"/MyHome/Board/BoardList.jsp\" style=\"text-decoration: none;\">Board</a> | \r\n");
      out.write("\t\t\t<a href = \"/MyHome/Index.jsp\" style=\"text-decoration: none;\">Home</a>\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t\t<div align=\"center\" id = \"main\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write(" <table border=\"1\" width = \"450\">\r\n");
      out.write(" \t<tr>\r\n");
      out.write(" \t\t<td>번호</td>\r\n");
      out.write(" \t\t<td>");
      out.print(dto.getNo() );
      out.write("</td>\r\n");
      out.write(" \t</tr>\r\n");
      out.write(" \t<tr>\r\n");
      out.write(" \t\t<td>아이디</td>\r\n");
      out.write(" \t\t<td>");
      out.print(dto.getId() );
      out.write("</td>\r\n");
      out.write(" \t</tr>\r\n");
      out.write(" \t \t<tr>\r\n");
      out.write(" \t\t<td>이름</td>\r\n");
      out.write(" \t\t<td>");
      out.print(dto.getName() );
      out.write("</td>\r\n");
      out.write(" \t</tr>\r\n");
      out.write(" \t \t<tr>\r\n");
      out.write(" \t\t<td>이메일</td>\r\n");
      out.write(" \t\t<td>");
      out.print(dto.getEmail() );
      out.write("</td>\r\n");
      out.write(" \t</tr>\r\n");
      out.write(" \t \t<tr>\r\n");
      out.write(" \t\t<td>전화번호</td>\r\n");
      out.write(" \t\t<td>");
      out.print(dto.getTel1() );
      out.write('-');
      out.print(dto.getTel2() );
      out.write('-');
      out.print(dto.getTel3() );
      out.write("</td>\r\n");
      out.write(" \t</tr>\r\n");
      out.write(" \t<tr>\r\n");
      out.write(" \t\t<td colspan=\"2\" align=\"right\">\r\n");
      out.write(" \t\t\t<input type=\"button\" value = \"수정\" onclick=\"location.href = '/MyHome/Member/UpdateForm.jsp'\">\r\n");
      out.write(" \t\t\t<input type=\"button\" value = \"회원탈퇴\" onclick=\"location.href = '/MyHome/Member/DeleteForm.jsp'\">\r\n");
      out.write(" \t\t</td>\r\n");
      out.write(" \t</tr>\r\n");
      out.write(" </table>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<div align=\"center\" class = \"footer\">KimMinJun's Work copyright。</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
